#! /usr/bin/env ruby

require 'thor'

class CI < Thor
  include Thor::Actions

  method_option :push, type: :boolean, aliases: '-p'

  desc 'build', 'creates docker image'
  def build
    run "docker build -t  #{get_image_name} ."
    test
    push
  end

  desc 'push', 'upload docker image'
  def push
    run "docker push #{get_image_name}" if options[:push]
  end

  desc 'test', 'run unit tests'
  def test
    run "docker run --rm #{get_image_name} npm run test"
  end

  private
  def get_branch_name
    @branch ||= run( 'git rev-parse --abbrev-ref HEAD', capture: true ).gsub(/\n/, '')
    return 'latest' if @branch === 'master'
    @branch
  end

  def get_image_name
    "richistron/gilded_rose_angular1:#{ get_branch_name }"
  end
end

CI.start(ARGV)
