#! /usr/bin/env ruby

require 'thor'

class CI < Thor
  include Thor::Actions

  method_option :push, type: :boolean, aliases: '-p'
  method_option :ignore_tests, type: :boolean
  method_option :ignore_build, type: :boolean

  desc 'build', 'creates docker image'
  def build
    run( "docker build -t  #{get_image_name} ." ) unless options[:ignore_build]
    test unless options[:ignore_tests]
    push if options[:push]
  end

  desc 'push', 'upload docker image'
  def push
    run "docker push #{get_image_name}"
  end

  desc 'test', 'run unit tests'
  def test
    run "docker run --rm #{get_image_name} npm run test"
  end

  private
  def get_branch_name
    @branch ||= run( 'git rev-parse --abbrev-ref HEAD', capture: true )
                  .gsub(/\n/, '')
    return 'latest' if @branch === 'master'
    @branch
  end

  def get_image_name
    "richistron/gilded_rose_angular1:#{ get_branch_name }"
  end
end

CI.start(ARGV)
